[package]
name = "ppcdis"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.1"
num-derive = "0.4.2"
num-traits = "0.2.18"
error = { path = "../error" }
thiserror = "1.0.58"
serde_yaml = "0.9.32"
serde = { version = "1.0.197", features = ["derive"] }

[dev-dependencies]
